apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-cpxv
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ixwr-tenant/rhtap-demo-app/hacbs-test-project-cpxv@sha256:ff0346adc861fad25c7ca03f1b1e9b17cc7f98477d1cfe481d53a6ef086fef72
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
